version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      # Enable 443 on production
      # - 443:443
    depends_on:
      - php
    volumes:
      - ./data/nginx:/app
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    image: php:fantasy
    restart: always
    depends_on:
      - redis
      - mariadb
    volumes:
      - ./data/nginx:/app

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - wordpress-db:/var/lib/mysql
      - ./data/nginx:/home
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress

  redis:
    image: redis
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - php

volumes:
  wordpress-db:
